In [ ]:
import pandas as pd 
import numpy as np
data = {'name':['wqwe','etfeg','fver','gdgr','bghf','hhrth'],'Age':[21,32,21,34,23,22],'salary':['1000','2000','3000','4000','5000','6000'],'Gender':['m','f','f','m','f','m']}
df = pd.DataFrame(data)
df

name  Age salary Gender
0   wqwe   21   1000      m
1  etfeg   32   2000      f
2   fver   21   3000      f
3   gdgr   34   4000      m
4   bghf   23   5000      f
5  hhrth   22   6000      m

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ff = df.iloc[:,1:3].values
final = ss.fit_transform(ff)
final

array([[-0.83683223, -1.46385011],
       [ 1.20875767, -0.87831007],
       [-0.83683223, -0.29277002],
       [ 1.5806831 ,  0.29277002],
       [-0.4649068 ,  0.87831007],
       [-0.65086951,  1.46385011]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
ss = MinMaxScaler()
ff = df.iloc[:,1:3].values
final = ss.fit_transform(ff)
final

array([[0.        , 0.        ],
       [0.84615385, 0.2       ],
       [0.        , 0.4       ],
       [1.        , 0.6       ],
       [0.15384615, 0.8       ],
       [0.07692308, 1.        ]])

In [ ]:
from sklearn.preprocessing import RobustScaler
ss = RobustScaler()
ff = df.iloc[:,1:3].values
final = ss.fit_transform(ff)
final

array([[-0.17647059, -1.        ],
       [ 1.11764706, -0.6       ],
       [-0.17647059, -0.2       ],
       [ 1.35294118,  0.2       ],
       [ 0.05882353,  0.6       ],
       [-0.05882353,  1.        ]])

In [ ]:
from sklearn.preprocessing import MaxAbsScaler
ss = MaxAbsScaler()
ff = df.iloc[:,1:3].values
final = ss.fit_transform(ff)
final

array([[0.61764706, 0.16666667],
       [0.94117647, 0.33333333],
       [0.61764706, 0.5       ],
       [1.        , 0.66666667],
       [0.67647059, 0.83333333],
       [0.64705882, 1.        ]])