In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df = pd.read_csv('/content/SalaryGender.csv')
df

Salary  Gender  Age  PhD
0    140.0       1   47    1
1     30.0       0   65    1
2     35.1       0   56    0
3     30.0       1   23    0
4     80.0       0   53    1
..     ...     ...  ...  ...
95    18.6       1   26    0
96   152.0       1   56    1
97     1.8       1   28    0
98    35.0       0   44    0
99     4.0       0   24    0

[100 rows x 4 columns]

In [ ]:
x = df.iloc[:,[0,1,2,3]].values
x

array([[140.  ,   1.  ,  47.  ,   1.  ],
       [ 30.  ,   0.  ,  65.  ,   1.  ],
       [ 35.1 ,   0.  ,  56.  ,   0.  ],
       [ 30.  ,   1.  ,  23.  ,   0.  ],
       [ 80.  ,   0.  ,  53.  ,   1.  ],
       [ 30.  ,   0.  ,  27.  ,   0.  ],
       [ 60.  ,   1.  ,  53.  ,   0.  ],
       [ 31.1 ,   0.  ,  30.  ,   0.  ],
       [125.  ,   1.  ,  44.  ,   1.  ],
       [ 51.  ,   1.  ,  63.  ,   1.  ],
       [  3.  ,   1.  ,  22.  ,   0.  ],
       [ 46.  ,   1.  ,  59.  ,   0.  ],
       [150.  ,   1.  ,  60.  ,   1.  ],
       [  3.  ,   1.  ,  28.  ,   0.  ],
       [130.  ,   1.  ,  65.  ,   0.  ],
       [ 15.  ,   0.  ,  25.  ,   0.  ],
       [130.  ,   1.  ,  65.  ,   0.  ],
       [ 84.  ,   0.  ,  47.  ,   1.  ],
       [190.  ,   1.  ,  66.  ,   1.  ],
       [ 74.  ,   1.  ,  45.  ,   1.  ],
       [ 73.  ,   0.  ,  46.  ,   0.  ],
       [ 10.  ,   0.  ,  24.  ,   0.  ],
       [ 50.  ,   0.  ,  60.  ,   0.  ],
       [  7.  ,   0.  ,  63.  ,   0.  ],
       [  9.5 , 

In [ ]:
arr = np.arange(11)
arr[4:9] = np.multiply(arr[4:9],-1)
print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
arr = np.array(arr)
print(arr[0].reshape((3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
rand = np.random.RandomState(30)
X = rand.randint(0, 30, (3, 3))
print(X)
np.sort(X, axis=0)

[[ 5  5 13]
 [13 20 12]
 [23  2 21]]


array([[ 5,  2, 12],
       [13,  5, 13],
       [23, 20, 21]])

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=4)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[1 2 3 4]]]]
number of dimensions : 4


In [ ]:
rand = np.random.RandomState(30)
X = rand.randint(0, 30, (3, 3))
print(X)
X[[0,2]] = X[[2,0]]
print(X)

[[ 5  5 13]
 [13 20 12]
 [23  2 21]]
[[23  2 21]
 [13 20 12]
 [ 5  5 13]]


In [ ]:
my_matrix = np.array([[1, 2, 1], [3, 4, 7], [3, 6, 3]])
print("Matrix")
for row in my_matrix:
    print(row)
rank = np.linalg.matrix_rank(my_matrix)
print("Rank of the given Matrix is : ",rank)

Matrix
[1 2 1]
[3 4 7]
[3 6 3]
Rank of the given Matrix is :  2
